name: Deploy via Docker Compose

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: self-hosted  # This runs on your EC2 instance's GitHub Runner

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: running docker compose
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Remove build cache
        run: docker system prune -a -f